### ISSUE TITLE
Limit requests in parallel

### ISSUE THREAD

**Issue by silviubmind** [MarkEdmondson1234/gago#7]
Hello Mark,

I am looking for an option/param/setup to limit gagocli, when doing all the requests in parallel, but can't find anything.

Also I've take a look at ya blog post:
https://code.markedmondson.me/gago/

Any idea how or If I could achive this with gagocli? 

Thx
Have a nice day

**Comment by MarkEdmondson1234** [comment]
Thanks :) in which way limit the requests? Number of rows or number or requests at a time? Why do you need to limit them?


________________________________

**Comment by silviubmind** [comment]
**Q: In which way limit the requests?** 
A: number of requests at a time.

**Q: Why do you need to limit them**
A: Caz quota limits (but I have increased the quota); Also, if I have two proceses running in paralel gagocli (asking for 2 diff things) in the same pipeline will fail with: "Error 503: The service is currently unavailable., backendError". As a solution I've put in serial the two proceses. 

Cheers

**Comment by MarkEdmondson1234** [comment]
Ok - the underlying requests are using this constant (`concurrencyLimit`) in `gago` that if you need today you could modify in the source code and recompile:

https://github.com/MarkEdmondson1234/gago/blob/master/gago/reports.go#L14

Its not available in a parameter (yet) but that could be added to `gagocli`.   

The underlying Google library (`google.golang.org/api/analyticsreporting/v4`) takes care of requests, does it not handle retries and backoff if over the limit?  Another alternative is to use one instance of `gagocli` for your two API requests as that should limit itself.
